# Generated by Django 2.2.11 on 2020-05-11 09:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0004_auto_20200415_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="last_visit",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 5, 11, 9, 20, 28, 9993)
            ),
        ),
    ]
