# Generated by Django 2.2.11 on 2020-05-11 09:23

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0006_auto_20200511_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="last_visit",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 5, 11, 9, 23, 8, 957977, tzinfo=utc)
            ),
        ),
    ]
