# Generated by Django 2.2.11 on 2020-05-11 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0007_auto_20200511_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="last_visit",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
